spring:
  application:
    name: auth-server
server:
  port: 7777
  servlet:
    context-path: /uua
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
