spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yichengjie/spring-cloud-config
          search-paths: SC-BOOK-CONFIG
  application:
    name: hello-git-server
server:
  port: 9090