spring:
  application:
    name: zuul-server
server:
  port: 5555
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
zuul:
  routes:
    client-a:
      path: /client/**
      serviceId: resource-server
  # 这里注意需要设置敏感请求头，否则header无法透传
  sensitive-headers:
security:
  oauth2:
    client:
      access-token-uri: http://localhost:7777/uua/oauth/token
      user-authorization-uri: http://localhost:7777/uua/oauth/authorize
      client-id: zuul_server # oauth2 客户端id
      client-secret: secret # oauth2 客户端密钥
    resource:
      jwt:
        key-value: spring_cloud123 # 使用对称加密方式，默认算法HS256